# Generated by Django 4.0.2 on 2022-02-23 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(default=None)),
                ('name', models.CharField(default=None, max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('presence_amount', models.PositiveSmallIntegerField(default=None)),
                ('level', models.CharField(default=None, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(default=None)),
                ('name', models.CharField(default=None, max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(default=None, max_length=100)),
                ('tatame_amount', models.PositiveSmallIntegerField(default=None)),
                ('id_academy', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='place_academy', to='api.academy', verbose_name='Sala/Local/Espaço')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('id_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_place', to='api.place', verbose_name='Sala/Local/Espaço')),
                ('id_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_teacher', to='api.teacher', verbose_name='Professor')),
            ],
        ),
    ]
