# Generated by Django 4.0.2 on 2022-02-24 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='id_classroom',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='group_classroom', to='api.classroom', verbose_name='Turma/Grupo/Alunos'),
            preserve_default=False,
        ),
    ]
