# Generated by Django 4.0.2 on 2022-02-24 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_group_id_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='id_student',
            field=models.ManyToManyField(related_name='group_student', to='api.Student'),
        ),
    ]
