# Generated by Django 3.0 on 2022-04-21 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220420_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Academy'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='academy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Academy'),
        ),
    ]
